### ISSUE TITLE
Use Semantic Versioning

### ISSUE THREAD

**Issue by mablae** [heidelpay/php-api#12]
Instead of using the "internal" HeidelPay Criterion API version as package version for this Api Client
composer/packagist, [semantic versioning](http://semver.org/lang/de/) could be used. 

SemVer makes maintaining BC with other implementations like the magento plugin easier and more stable. 

Related to #11

**Comment by frostblogNet** [comment]
I'm familiar with this visioning semantic and yes it has some advantages, but I don't like it, I'm more into the ubuntu way https://en.wikipedia.org/wiki/Software_versioning#Date_of_release. This makes it easier for our support to see if somebody uses the latest version.

**Comment by mablae** [comment]
I don't understand that argument with customer support:
The support needs to know which one is the current stable version in both cases to be helpful?

When just looking at the installed version (date) all they could do is "guess", if there was "maybe" a never release in meantime? Or did I totally misunderstood you? 

It is also less about liking something here. It is about applying industry standards.

http://semver.org/#why-use-semantic-versioning
