### ISSUE TITLE
Idea: Move examples to an external repository

### ISSUE THREAD

**Issue by mablae** [heidelpay/php-api#13]
The examples could be moved to an separate repository and then "require" this package.

**Comment by frostblogNet** [comment]
Thatś true and in process. ;)

**Comment by tburschka** [comment]
Also the paths to the composer autoload.php should be updated for every example, some have older paths like

    require_once __DIR__.'/../../../autoload.php';

instead of

    require_once __DIR__.'/../autoload.php';

**Comment by heidelpay** [comment]
autoloader path issue is fixed in #25

**Comment by rokde** [comment]
The path to autoload.php does not work on any of the examples. You have to change it to `require_once __DIR__ . '/../vendor/autoload.php';` to make it work. I have done that in the `_enableExamples.php` and removed it in all other files.
