### ISSUE TITLE
Idea: Throw exceptions on errors

### ISSUE THREAD

**Issue by mablae** [heidelpay/php-api#14]
Instead of wrapping curl/transport errors in the `Response`, 
exceptions should be thrown, like this:

```
ClientException
 -- TransportException
 -- MissingParameterException
```
and so on. The original response could then be wrapped in the exceptions object, so you could do: 

```php
<?php 

try  {    

    $response =  $sofort->getRequest()->send($sofort->getPaymentUrl(), $request);

} catch (ClientException $e) {

    if ($e->hasResponse())
        $faultyResponse = $e->getResponse()
    }
}
```

**Comment by frostblogNet** [comment]
Good idea . We will have a look how this could be integrated

**Comment by heidelpay** [comment]
The idea is good but we do not want to have two different way of handling an response error for sync and response.
