### ISSUE TITLE
Idea: Always return an first class Response (BC Break)

### ISSUE THREAD

**Issue by mablae** [heidelpay/php-api#15]
Instead of wrapping `Response` object in an array representation, the `Response` should contain the original data and make it available in a method (i.e 
`::getRawResponseArray()`) in the `Response` object itself. 

This breaks BC.

**Comment by frostblogNet** [comment]
I can understand your idea but I want to have a clean response object without the RawResponse Data in it.

**Comment by mablae** [comment]
But having `return array($rawArray, new Response($rawArray))` is just bad design. 

I thought it is to maintain BC only?
