### ISSUE TITLE
Mcrypt required dependency?

### ISSUE THREAD

**Issue by tburschka** [heidelpay/php-api#18]
In the composer.json mcrypt is a required dependency but the php api seems not to use mcrypt.
Also: Mcrypt is deprecated (see: http://php.net/manual/de/migration71.deprecated.php) as well it's not suggested to use (see: https://paragonie.com/blog/2015/05/if-you-re-typing-word-mcrypt-into-your-code-you-re-doing-it-wrong).

**Comment by heidelpay** [comment]
You are right mcrypt is not required we will remove the dependency. 

Thanks

**Comment by heidelpay** [comment]
mcrypt dependency has been removed in #25.

Thx @tburschka
