### ISSUE TITLE
Task: Add MarketplaceParameterGroup

### ISSUE THREAD

**Issue by heidelpay** [heidelpay/php-api#23]
The MarketplaceParameterGroup should be added. To make the php-api even useful for market place integrations.

**Comment by MieterEngel** [comment]
I'm going to start with at least some basic parameters

**Comment by heidelpay** [comment]
Just to let you know. marketplace can also be used over the basket api. We currently also built an sdk for the basket api but the first versions will also not include the marketplace parameter. But regarding to our core development basket api will be preferred. So if you need an early access to the basket sdk. Please let us know.

**Comment by MieterEngel** [comment]
sure, that would be great! Can you send me some infos / files on that?

**Comment by heidelpay** [comment]
Hello @MieterEngel !

I've just published our current state of the php-basket-api to the https://github.com/heidelpay/php-basket-api repository. Feel free to use it, but keep in mind that it is meant for development use until we make the first release.

Regards,
Stephano
