### ISSUE TITLE
Ensure Compatibility for lowest Version Constraints

### ISSUE THREAD

**Issue by Blackskyliner** [heidelpay/php-api#31]
Currently Travis will always check for highest package compatibility, but not for lowest package compatibility.

An extra Travis check for:

```
composer update --prefer-lowest
```

should be added to ensure compatibility even with the lowest supported versions resolved by the composer dependency version requirements.

**Comment by heidelpay** [comment]
Hello,

we have removed this test currently because there are no dependencies where compser covers the lowest dependency. 

Regards
