### ISSUE TITLE
Add documentation tables for states and stuff as 'const' code Interfaces

### ISSUE THREAD

**Issue by Blackskyliner** [heidelpay/php-api#32]
It would be way better to have all constants, return values and codes, which may get returned from the API as constants. (maybe behind an interface or abstract class)
Currently you would have to use magic numbers on some of them like

```php
$heidelpay = new Response($_POST);
// ...
// 100.396.101   transaction cancelled by user
$heidelpay->getProcessing()->getReturnCode() === '100.396.101'
```

and you would have to guess or know that it's about an cancelation of the process by the user.
Other example would be the StatusCodes that may get returned:

```php
$heidelpay = new Response($_POST);
// ...

// 60   REJECTED_BANK
// 65   REJECTED_RISK
// 70   REJECTED_VALIDATION
if ($heidelpay->getProcessing()->getStatusCode() === '60' ||
    $heidelpay->getProcessing()->getStatusCode() === '65' ||
    $heidelpay->getProcessing()->getStatusCode() === '70'
) {
    // ...
}
```

**Comment by heidelpay** [comment]
Hello,
as mentioned in your other issue please use the nativ error handling for the api https://dev.heidelpay.de/quick-start-quide-php-api/#Error_handling. 

I can agree with you that it would be nice to have an interface or an abstract class with the return values. But we can currently not support this.

Regards
