### ISSUE TITLE
How to handle all the "not success" or "zero/negative cash flow" cases?

### ISSUE THREAD

**Issue by Blackskyliner** [heidelpay/php-api#33]
The Examples only state how everything works in a success/positive manner.
What about error handling? How is it done right?

For example, how do I process a chargeback? What do I get there and what does really matter? I guess I will get my shop transaction ID for that payment with a new unique id regarding the chargeback I guess?

My naive try at this is currently to check for .CB

```php
$heidelpay = new Response($_POST);
$transaction = $heidelpay->getIdentification()->getTransactionId();
// .CB === Chargeback
if (strpos($heidelpay->getPayment()->getCode(), '.CB') !== false) {
    // mark as chargeback
}
```

Also what about the case of rejection?

Currently I got stuff like
```php
$heidelpay = new Response($_POST);
// 60   REJECTED_BANK
// 65   REJECTED_RISK
// 70   REJECTED_VALIDATION
if ($heidelpay->getProcessing()->getStatusCode() === '60' ||
    $heidelpay->getProcessing()->getStatusCode() === '65' ||
    $heidelpay->getProcessing()->getStatusCode() === '70'
) {
    // mark as rejected
}
```

Also what stuff should I check to know if a user for example aborted a payment via Paypal or Sofortüberweisung?

Currently I got:

```php
$heidelpay = new Response($_POST);
if ($heidelpay->getProcessing()->getResult() === 'NOK' ||
    // 100.396.101   transaction cancelled by user
    $heidelpay->getProcessing()->getReturnCode() === '100.396.101'
) {
    // mark as cancelled
}
```

I know I could go through all the associated .pdf documents related to the raw api, but it would be way more comfortable to have at least one example for such stuff directly within the php-api documentation/examples. To ease development and reduce trial&error programming against the test api.

**Comment by heidelpay** [comment]
hello,

to your first question: 
Chargebacks are currently not covered by the sdk. Heidelpay has a different api for this. It´s called push notification and works pretty match like sms notification. We ware currently working on a extension of the php-api. Which will be able to map such a notification with is xml to the object used in the php-api. 

Now to your second question:
The response object has a isError, isSuccess and isPending function. If isError return true, you can use getError(). (see [here](https://github.com/heidelpay/php-api/blob/master/example/HeidelpayResponse.php#L53)) This will give you the error code and message in return. Most of the messages are not designed to be shown to the store customer. You can use our [php-customer-messages ](https://github.com/heidelpay/php-customer-messages)lib for this.

Please also have a look into our quick guide https://dev.heidelpay.de/quick-start-quide-php-api/

Regards

**Comment by Blackskyliner** [comment]
So what about the cancelation/abortion of the payment via Paypal or Sofort? (Like when the user cancels the transaction midway and returns to the store-website)
 
Is that an Error, Success or Pending or the stated ReturnCode 100.396.101?

---

I also guess from that description, that a rejection is currently "merged" into the error state?
And I would then have to either manually check the status codes like I already do to know exactly what type of error-type happened?

Text-Error-Message (getError()) parsing is not something I would like use to verify my state if possible... As I would have to adapt my application if those someday change to a different format...

---

Currently it's all about the data structure and how to model it into my current system of payment states. The information I later show to the user are not directly dependent on the Heidelpay api but on the states I try to guess about the current payment state and have persisted on my end.

Essentially what I try to do is mapping the API Responses I get to the following States of my application:

```php
const STATE_OK = 'ok';
const STATE_ERROR = 'error';
const STATE_PENDING = 'pending';
const STATE_REJECTED = 'rejected';
const STATE_CANCELED = 'canceled';
```

So I can, for example show a history about the payment states within the backend to resolve problems if a user inquires information about the current state of a payment.

Is it even possible to map all those states via the API responses or would I have to let some of them unmapped because there is no such state for the Heidelpay API?

---

Regarding Chargebacks, so I currently have no way but to manually handle them for now?

**Comment by heidelpay** [comment]
The sdk is designed to simplify the underlying ngw api. So it does only handle;

ACK = ok
ACK, with StatusCode 80 = Pending
NOK = error, canceled etc

But you are right, you can use the status code to separate. But there is no distinction be canceled by user and nok ok.

CodeStatus
00   SUCCESS 
40  NEUTRAL 
59  WAITING_BANK
60 REJECTED_BANK 
65 REJECTED_RISK 
70 REJECTED_VALIDATION 
80 WAITING 
90 NEW 

Chageback can be handle by using our query api or by using our push notification. Currently there is no sdk for this. Please write a mail to development@heidelpay.de and we will send you the api documentation. 

regards
