### ISSUE TITLE
Access to clearing properties of payment method response

### ISSUE THREAD

**Issue by bkonetzny** [heidelpay/php-api#44]
As far as I can see, there is no access to the clearing properties provided by the payment method response.
Is there any reason not to provide these via a mapper like the other properties?

As far as I know, the `CLEARING_{x}` properties match the given `PRESENTATION_{x}` properties of the `$_POST` data, but might differ due to actual cleared data, so relying on the `PRESENTATION_{x}` values seems not to be ok?

Presentation values are exposed in `getPresentation()` on the response, should an `getClearing()` be added to return the actual cleared values (`CLEARING_AMOUNT`, `CLEARING_CURRENCY` and `CLEARING_DESCRIPTOR`)?

**Comment by heidelpay** [comment]
Hi @bkonetzny ,

the only reason why it is not in, is that we do not have any case where we need this information currently. But should be simple to add it. We will put it on the list or if you will make a merge request.

Regards
JR

**Comment by bkonetzny** [comment]
Hi JR,

I could do a merge request, if this information is really needed.
Currently, I try to migrate a legacy API call application to the PHP-API SDK. In the legacy code we use the clearance fields to check for the actual cleared data. If you tell this doesn't make sense and we can always use the presentation fields, I will change our code. But if you confirm that clearance might differ from presentation, I'll do a pull request.

Thanks for feedback! :)

**Comment by heidelpay** [comment]
Hi @bkonetzny,

haven't seen one, but we will check it and I will send you the answer on Monday.

Regards
JR

**Comment by heidelpay** [comment]
Sorry for the late response. But we hat to make sure that it is like I had expected. Prasentation and Clearing amount are the same. They both are built from the xml Parameter Payment->Clearing->Amount 

Regards
Jens

**Comment by bkonetzny** [comment]
Hi Jens,

thanks for the clarification, so I will use data from "Presentation" and not from "Clearance".
Closing this issue! :)

Regards
Bastian
