### ISSUE TITLE
"PRESENTATION.AMOUNT does not match expected configurations" when amount is float

### ISSUE THREAD

**Issue by bkonetzny** [heidelpay/php-api#51]
We are trying to refund a payment with an amount of `20.9000`, which is a valid float in PHP.
When we submit this, we get the error `PRESENTATION.AMOUNT does not match expected configurations` from the API.

```
$paymentMethod->getRequest()->basketData(
    null,
    20.9000,
    'EUR'
);
```

According to the docs (`Heidelpay\PhpApi\ParameterGroups\PresentationParameterGroup`), `setAmount` should be called with a `float` (example is `@param float $amount f.e. 20.12`), whis is exaclty what we do here. When we do the same call with `20.90`, everything works as expected.

```
$paymentMethod->getRequest()->basketData(
    null,
    20.90,
    'EUR'
);
```

Can you please clarify how this should be handled?
* Should the SDK handle this and convert the float to expected format, e.g. 2 digits?
* Should the calling code convert to 2 digits when passing the value to `basketData`?

**Comment by stevenobird** [comment]
Hello,

our API wants the Presentation.Amount formatted as a float with 2 decimal places. Since we don't want to change any data given by the developer, so you'll have to manage that by yourself.

Well will add that important information to our documenation and docblocks, thanks for the issue!

Regards,
Stephano

**Comment by bkonetzny** [comment]
Hi Stephano,

thanks for clarification, we will adjust our code! :)

Regards,
Bastian

**Comment by stevenobird** [comment]
You're welcome!

Kind regards,
Stephano
