### ISSUE TITLE
Error on redirect after successful payment with cookies disabled

### ISSUE THREAD

**Issue by bkahraman** [heidelpay/php-api#52]
If cookies are disabled in browser, redirection (payment/wizard/merchantRedirect) after payment fails with following message: "Bad Request Error: Not Found".

I have compared the content of my `Heidelpay\PhpApi\Request Object` for both cases (with and without cookies enabled) and all values except of transaction id are matching. So I don't know what to check else.

Would be grateful for every hint about this error (e.g. what exactly could not be found).

**Comment by heidelpay** [comment]
Hi @bkahraman,

I am not sure if I really understand your  question, but I don't think this error is related to our php-api. The error seems to be in the way of your integration. Our payment does not care about cookies. It will just return the customer back to your redirect page, which you have defined in your reponse page. The only way to handle browsers with disabled cookies is to put the session into a Get parameter of this redirect url. Of course this is no good solution, but 302 redirects does not care about post parameters.  So you can only identify  the customer on the cookie or on a get parameter. 

Hope this will help you.

Regards
Jens

**Comment by bkahraman** [comment]
Hi Jens,

thanks for the quick response! And sorry for not describing the problem more detailed.
We already pass the session id as url parameter to the redirect url. However it seems to fail one step before the actual redirection. This is what we get after successful payment:
![image](https://user-images.githubusercontent.com/5645840/32052968-0c464f56-ba5a-11e7-88ed-d097195ffb96.png)
Do you have an idea, what is causing the 404 error there?

Best,
Burak

**Comment by heidelpay** [comment]
Hi @bkahraman 

looks like a Klarna/Sofort related issue. We will check it and forward it to  our Klarna contact,

Regards

Jens

**Comment by bkahraman** [comment]
Ok thanks @heidelpay !
And please keep me updated.

Kind regards,
Burak

**Comment by bkahraman** [comment]
Hi @heidelpay, 

did you already get any feedback from Klarna?

Best,
Burak

**Comment by sixer1182** [comment]
Hi @bkahraman,
we contacted Klarna regarding the error you described since we were able to reproduce it.
We will keep you posted about their response.

Feel free to contact Klarna directly via https://www.klarna.com/sofort/business/haendler-support/support-hotline/deutschland/

Best regards,
simon

**Comment by sixer1182** [comment]
Hi @bkahraman,
here is a brief update.
Klarna is busy finding the problem and promised to keep me informed.

Best regards,
simon

**Comment by sixer1182** [comment]
Hi @bkahraman,
Klarna just contacted me to tell me they found and fixed the problem, which I was able to verify.
Please check on your system and post a new ticket if the problem persists.

Best regards,
simon

**Comment by bkahraman** [comment]
Thanks a lot @sixer1182 just tested it and can confirm that it's working.

Kind regards,
Burak
