### ISSUE TITLE
Idea: Decide on a CodeStyle and enforce it with QA Tools

### ISSUE THREAD

**Issue by mablae** [heidelpay/php-api#9]
The lib should follow a Coding Style like PSR-2 and enforce it with `php-cs-fixer` for example.

**Comment by mablae** [comment]
The PR #8 contains a basic PSR-2 based Coding Style that is tested then with 
[php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) during Travis CI builds. 

This will ensure style consistency in the codebase in an easy way.

**Comment by stevenobird** [comment]
Applying Coding Styles like PSR-2 is a good idea, but right now, we are working on other things like extracting php-api examples to external repositories and creating helper libraries.
When these things are done, testing and coding styles are way more relevant then yet, I guess. :)

**Comment by mablae** [comment]
hey @stevenobird, 

I think exactly the other way: Fundamentals first. 😄 

This stuff can be easy automated with Tools like [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)

@frostblogNet already merged this: [Example file](https://github.com/heidelpay/php-api/blob/develop/.php_cs) 
It is the PSR-2 CodeStyle + some additional flags from the Symfony Style that is even stricter.

To enforce the coding style just run before pushing changes. 
```bash
php bin/vendor/php-cs-fixer fix --diff --dry-run
```

What do you mean with "helper libraries" ?

**Comment by heidelpay** [comment]
Thx @mablae for the improvment.
